from turtle import *

def prep():
    global squirtle, wartortle, uguu, blastoise, memez
    
    setup(width=1360, height=750)

    colormode(255)

    bgcolor("gray")

    squirtle = Turtle()
    wartortle = Turtle()
    blastoise = Turtle()
    memez = Turtle()
    uguu = Turtle()

    squirtle.speed(9)
    wartortle.speed(9)
    blastoise.speed(9)
    memez.speed(9)
    uguu.speed(9)

    uguu.shape("turtle")
    squirtle.shape("turtle")
    wartortle.shape("turtle")
    blastoise.shape("turtle")
    memez.shape("turtle")

def create_box(name1):
    for i in range(4):
        name1.forward(520)
        name1.right(90)
    name1.forward(260)
    name1.right(90)
    name1.forward(520)
    name1.right(90)
    name1.forward(260)
    name1.right(90)
    name1.forward(260)
    name1.right(90)
    name1.forward(520)

def pokeball(name2):
    name2.begin_fill()
    for i in range(1,5):
        name2.forward(80)
        name2.left(90)
        name2.forward(20)
        name2.right(90)
        name2.forward(40)
        name2.left(90)
        name2.forward(20)
        name2.right(90)
        name2.forward(20)
        name2.left(90)
        name2.forward(40)
        name2.right(90)
        name2.forward(20)
        name2.left(90)
    name2.end_fill()

def button(name5):
    name5.color(255, 255, 255)
    name5.begin_fill()
    i = 0
    while i < 4:
        name5.forward(40)
        name5.left(90)
        i += 1
    name5.end_fill()

def pokeball_top():
    memez.begin_fill()
    memez.forward(80)
    memez.right(90)
    memez.forward(20)
    memez.left(90)
    memez.forward(40)
    memez.right(90)
    memez.forward(40)
    memez.left(90)
    memez.forward(20)
    memez.right(90)
    memez.forward(40)
    memez.right(90)
    memez.forward(20)
    memez.left(90)
    memez.forward(20)
    memez.right(90)
    memez.forward(40)
    memez.right(90)
    memez.forward(20)
    memez.left(90)
    memez.forward(20)
    memez.right(90)
    memez.forward(20)
    memez.left(90)
    memez.forward(40)
    memez.left(90)
    memez.forward(20)
    memez.right(90)
    memez.forward(20)
    memez.left(90)
    memez.forward(20)
    memez.right(90)
    memez.forward(40)
    memez.right(90)
    memez.forward(20)
    memez.left(90)
    memez.forward(20)
    memez.right(90)
    memez.forward(40)
    memez.right(90)
    memez.forward(20)
    memez.left(90)
    memez.forward(40)
    memez.right(90)
    memez.forward(40)
    memez.left(90)
    memez.forward(20)
    memez.end_fill()

def pokeball_bottom(name4):
    name4.color(255, 255, 255)
    name4.begin_fill()
    name4.forward(80)
    name4.left(90)
    name4.forward(20)
    name4.right(90)
    name4.forward(40)
    name4.left(90)
    name4.forward(40)
    name4.right(90)
    name4.forward(20)
    name4.left(90)
    name4.forward(20)
    name4.left(90)
    name4.forward(20)
    name4.left(90)
    name4.forward(20)
    name4.right(90)
    name4.forward(60)
    name4.left(90)
    name4.forward(20)
    name4.right(90)
    name4.forward(40)
    name4.right(90)
    name4.forward(20)
    name4.left(90)
    name4.forward(60)
    name4.right(90)
    name4.forward(20)
    name4.left(90)
    name4.forward(20)
    name4.left(90)
    name4.forward(20)
    name4.left(90)
    name4.forward(20)
    name4.right(90)
    name4.forward(40)
    name4.left(90)
    name4.forward(40)
    name4.right(90)
    name4.forward(20)
    name4.end_fill()
    
def squirtles_job():
    squirtle.penup()
    squirtle.right(90)
    squirtle.forward(260)
    squirtle.left(90)
    squirtle.forward(260)
    squirtle.left(180)
    squirtle.pendown()
    create_box(squirtle)
    squirtle.hideturtle()

def wartortles_job():
    wartortle.showturtle()
    wartortle.right(180)
    wartortle.forward(170)
    wartortle.right(90)
    wartortle.penup()
    wartortle.forward(10)
    wartortle.pendown()
    wartortle.right(90)
    pokeball(wartortle)
    wartortle.penup()
    wartortle.forward(260)
    wartortle.pendown()
    pokeball(wartortle)
    wartortle.right(90)
    wartortle.penup()
    wartortle.forward(260)
    wartortle.pendown()
    wartortle.left(90)
    pokeball(wartortle)
    wartortle.right(180)
    wartortle.penup()
    wartortle.forward(260)
    wartortle.pendown()
    wartortle.right(180)
    pokeball(wartortle)
    wartortle.hideturtle()

def blastoises_job():
    blastoise.showturtle()
    blastoise.penup()
    blastoise.right(180)
    blastoise.forward(170)
    blastoise.right(90)
    blastoise.forward(30)
    blastoise.right(90)
    blastoise.pendown()
    pokeball_bottom(blastoise)
    blastoise.left(90)
    blastoise.penup()
    blastoise.forward(260)
    blastoise.pendown()
    pokeball_bottom(blastoise)
    blastoise.penup()
    blastoise.forward(260)
    blastoise.left(90)
    blastoise.pendown()
    pokeball_bottom(blastoise)
    blastoise.right(90)
    blastoise.penup()
    blastoise.forward(260)
    blastoise.right(180)
    blastoise.pendown()
    pokeball_bottom(blastoise)
    
def memez_job():
    memez.color("red")
    memez.showturtle()
    memez.right(180)
    memez.penup()
    memez.forward(170)
    memez.right(90)
    memez.forward(230)
    memez.right(90)
    memez.pendown()
    pokeball_top()
    memez.color("yellow")
    memez.right(90)
    memez.penup()
    memez.forward(260)
    memez.pendown()
    pokeball_top()
    memez.color("green")
    memez.right(180)
    memez.penup()
    memez.forward(260)
    memez.pendown()
    memez.left(90)
    pokeball_top()
    memez.color("blue")
    memez.left(90)
    memez.penup()
    memez.forward(260)
    memez.right(180)
    memez.pendown()
    pokeball_top()

def uguus_job():
    uguu.showturtle()
    uguu.penup()
    uguu.right(180)
    uguu.forward(150)
    uguu.right(90)
    uguu.forward(90)
    uguu.right(90)
    uguu.pendown()
    button(uguu)
    uguu.penup()
    uguu.forward(260)
    uguu.pendown()
    button(uguu)
    uguu.right(90)
    uguu.penup()
    uguu.forward(260)
    uguu.left(90)
    button(uguu)
    uguu.right(180)
    uguu.penup()
    uguu.forward(260)
    uguu.right(180)
    button(uguu)
    
prep()
uguu.hideturtle()
wartortle.hideturtle()
blastoise.hideturtle()
memez.hideturtle()
squirtles_job()
wartortles_job()
memez_job()
blastoises_job()
uguus_job()
